# Generated by Django 4.2.3 on 2023-07-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_line', models.CharField(max_length=100)),
                ('mid_line', models.CharField(max_length=100)),
                ('bottom_line', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Преимущество',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Пункт',
            },
        ),
    ]
