# Generated by Django 4.2.3 on 2023-07-07 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Преимущество', 'verbose_name_plural': 'Преимущества'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Пункт', 'verbose_name_plural': 'Пункты'},
        ),
    ]
