# Generated by Django 4.2.3 on 2023-07-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elon', '0003_alter_feature_bottom_line_alter_feature_mid_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='link',
            field=models.CharField(default=123, max_length=500, verbose_name='Ссылка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
